name:                bitcoin
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/bonfacekilz/bitcoin_tutorial#readme
license:             BSD3
author:              Bonface M. K.
maintainer:          bonfacemunyoki@gmail.com
copyright:           2019 Bonface K. M.
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

executables:
  bitcoin:
    source-dirs:      src
    main:             Main.hs
